server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: theatre-service
          uri: http://localhost:8081
          predicates:
            - Path=/theatres/**

        - id: movie-service
          uri: http://localhost:8082
          predicates:
            - Path=/movies/**

        - id: booking-service
          uri: http://localhost:8083
          predicates:
            - Path=/bookings/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
