spring:
  datasource:
    url: jdbc:h2:mem:theatre_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
